server:
  port: 8080
spring:
  webflux:
    base-path: bitcoin-spv
  application:
    name: ms-personal-btc
  r2dbc: 
    url: r2dbc:pool:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      validation-query: SELECT 1

bitcoin:
  network:
    profile: ${BTC_NETWORK_PROFILE} #main/test
  wallet:
    name: test
    path: ${BTC_WALLET_PATH}
  transaction:
    minConfirm: 6